main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'
# this list contains the urls of the app functionalities
urlpatterns = [
    url(r'^login$', views.login, name='login'),
    url(r'^do-login$', views.doLogin, name='doLogin'),
    url(r'^do-logout$', views.doLogout, name='doLogout'),
    url(r'^home$', views.home, name='home'),
    url(r'^map$', views.map, name='map'),
    url(r'^reservoir-detailed-info$', views.reservoirDetailedInfo, name='reservoirDetailedInfo'),
    url(r'^reservoir-list$', views.reservoirList, name='reservoirList'),
    url(r'^export$', views.exportMeasurementData, name='exportData'),
    url(r'^measurement-data$', views.measurementData, name="measurementData"),
    url(r'^reservoir-data$', views.reservoirData, name="reservoirData"),
    url(r'^$', views.main, name='main'),
]

water_sensor/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # this will route the base url to the main configuration
    url(r'^', include('main.urls')),
]

main/models/Connection.py
from django.db    import models

from .models_conf import *
from .Reservoir import Reservoir

class Connection (models.Model) :
    """
    Represents a connection between 2 reservoirs
    """

    # id of this object
    con_id       = models.AutoField(primary_key=True)
    # the length of the piping in the conexion
    pipingLength = models.FloatField() # meters
    # maximum flow of water supported by this conexion
    maxFlow      = models.FloatField() # cubic meters / second
    # the reservoirs that are connected
    reservoirA   = models.ForeignKey(Reservoir, related_name='A_con')
    reservoirB   = models.ForeignKey(Reservoir, related_name='B_con')
    # from a to b (if positive), b to a (if negative)  or bidirectional (if 0)
    flowDirection = models.IntegerField()

main/models/InputPoint.py
from django.db    import models

from .models_conf import *
from .Reservoir import Reservoir

class InputPoint (models.Model) :
    """
    A point of water entry in the reservoir
    """

    # the id of this object
    inPoint_id = models.AutoField(primary_key=True)
    # the reservoir it belongs to
    reservoir = models.ForeignKey(Reservoir, on_delete=models.CASCADE)

main/models/Measurement.py
from django.db    import models
from enum         import Enum
from django.utils import timezone

from .models_conf import *
from .Reservoir import Reservoir

class Measurement (models.Model) :
    """
    A periodic measurement of the water level and quality
    Water quality is given by it's pH and conductivity
    """


    # the id of this measurement
    mes_id       = models.AutoField(primary_key=True)
    # the reservoir this measurement belongs to
    reservoir    = models.ForeignKey(Reservoir)
    # date and time of reading
    dateTime = models.DateTimeField(default=timezone.now)
    # height of water in the reservoir
    waterLevel   = models.FloatField(default=-1)
    # pH of the water
    pH           = models.FloatField(default=-1)
    # conductivity of the water
    conductivity = models.FloatField(default=-1)
    # salinity of the water
    salinity     = models.FloatField(default=-1)
    # total disolved solids in the water
    tds          = models.FloatField(default=-1)
    # the number of the package corresponding to this measurement
    packetNr     = models.IntegerField()

    def waterQuality (self) :
        """
        Returns a measure of water quality according to pH and conductivity
        """
        # TODO: implement
        pass


    def waterVolume (self) :
        """
        Returns the quantity of water in the reservoir according to this measurement.

        Returns
        -------
        float
        """

        return self.waterLevel*self.reservoir.width*self.reservoir.length

    ## TODO: get only the attributes specified in data
    ## TODO: at this point everything is being retrieved
    def get (reservoirs, data, clusterBy, dateFrom, dateUntil) :
        """
        Returns a set of measurements filtered by 'dataFilter'.

        Parameters
        ----------
        reservoirs: int
            The reservoirs to get measurements. If it is 'all' or '' every reservoir will be considered.
        data: str
            Specifies the attribute to read. If it is 'all' or '' every attribute will be read.
        clusterBy: [str]
            Indicates how to distinguish the data (by hours, days(averages), months(averages))
        dateFrom: str
            Measurements should have dateTime value after, or at, this date
        dateUntil: str
            Measurements should have dateTime value before, or at, this date
        Returns
        -------
        QuerySet
        """

        # choose how to group values
        selectedValues =  clusterBy.split(',')

        dtFrom  = timezone.datetime.strptime(dateFrom, '%Y-%m-%d')
        dtUntil = timezone.datetime.strptime(dateUntil, '%Y-%m-%d')

        measurements =  Measurement.objects \
            .extra(select={'minute': 'minute(dateTime)', 'hour': 'hour(dateTime)', \
                  'day': 'day(dateTime)', 'month': 'month(dateTime)', 'year': 'year(dateTime)'}) \
            .filter(dateTime__gt=dtFrom, dateTime__lte=dtUntil)

        if reservoirs != 'all' :
            reservoirsAccpeted = reservoirs.split(',')
            measurements = measurements.filter(reservoir__res_id__in=reservoirsAccpeted)

        measurements = measurements.order_by(*selectedValues) \
            .values(*selectedValues) \
            .annotate(
                waterLevel=models.Avg('waterLevel'),
                pH=models.Avg('pH'),
                conductivity=models.Avg('conductivity'),
                salinity=models.Avg('salinity'),
                tds=models.Avg('tds'))

        return measurements
        

main/models/OutputPoint.py
from django.db    import models

from .models_conf import *
from .Reservoir import Reservoir

class OutputPoint (models.Model) :
    """
    A point of water exit in the reservoir
    """

    # the id of this object
    outPoint_id = models.AutoField(primary_key=True)
    # the reservoir it belongs to
    reservoir = models.ForeignKey(Reservoir, on_delete=models.CASCADE)

main/models/Pump.py
from django.db    import models

from .models_conf import *


class Pump (models.Model) :
    """
    Represents a water extraction an pumping site
    """

    # id of this pump
    pump_id = models.AutoField(primary_key=True)
    # the maximum daily water production capacity
    maxProdCapacity = models.FloatField()  # cubic meters / day
    # the maximum pumping capacity
    maxPumpingCapacity = models.FloatField() # cubic meters / second
    # the specific location of the pump
    latitude  = models.FloatField()
    longitude = models.FloatField()
    # island where the pump is located
    island    = models.CharField(max_length=MAX_STR_SIZE)
    # county(concelho) where the pump is located
    county  = models.CharField(max_length=MAX_STR_SIZE)
    # the town where the pump is located
    town      = models.CharField(max_length=MAX_STR_SIZE)

    def addressName (self) :
        """
        Builds a printable address of the pump's location.

        Returns
        -------
        str
        """

        return "{}, {}, {}, @({}, {})".format(
                self.town, self.county, self.island, self.latitude, self.longitude)

main/models/models_conf.py
# defines the maximum size of a string
MAX_STR_SIZE = 256
# defines the maximum size of a directory or file path
MAX_PATH_SIZE = 500

main/views.py
from django.shortcuts import render, redirect
from django.http      import HttpResponse, Http404
from django.template  import loader
from django.conf      import settings
from django.utils     import timezone

from django.contrib.auth            import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models     import User
from django.forms.models            import model_to_dict
from django.core.exceptions         import FieldError, SuspiciousOperation
from django.db.models               import Q
from django.db.models.functions     import Concat, Extract

import django.contrib.auth as auth

from datetime import datetime

import json, csv, xlwt

from .models import *


def main (req) :
    """
    opens the main page or the presentation page
    """
    siteDesc = "Nós somos um grupo de estudantes e professores da Universidade \
     de Cabo Verde, em Cabo Verde, e da Universidade de Wellesley, \
     Boston USA, que tivemos uma idea para monitorizar o nível e a \
     qualidade de água em reservatórios de distribuição de agua em Cabo Verde. \
    "

    template = loader.get_template('main/intro.html')
    return HttpResponse(template.render({'site_desc': siteDesc}, req))


def login (req) :
    """
    Returns the login page
    """

    template = loader.get_template('main/login.html')
    return HttpResponse(template.render({}, req))


def doLogin (req) :
    """
    This function does the actual login verification. It checks the credentials
    and returns error messages or an ok and saves the user session.
    """

    username = req.POST['username']
    password = req.POST['password']

    # search for a user with the username
    try :
        User.objects.get(username=username)
    except User.DoesNotExist :
        # return username error
        print("[doLogin] invalid username")
        res = '{"state":"err", "err": "username"}'
        return HttpResponse(res)

    user = authenticate(username=username, password=password)
    # check password
    if user is not None :
        # save session
        auth.login(req, user)
        print("[doLogin] login succeded")
    else:
        # return password error
        print("[doLogin] invalid password")
        res = '{"state":"err", "err": "password"}'
        return HttpResponse(res)

    # go to the home page
    return HttpResponse('{"state": "ok"}')


@login_required(login_url='/login')
def doLogout (req) :
    auth.logout(req)
    return redirect('/login')


@login_required(login_url='/login')
def home (req) :
    """
    Returns the home page
    """

    template = loader.get_template('main/home.html')
    return HttpResponse(template.render({}, req))


@login_required(login_url='/login')
def map (req) :
    """
    Returns a page with a map with the locations of the reservoirs, pumps and the conections.
    Maps can be show with all the information, can be shown with information focused on
    just one reservoir and its connections or focused on one region and its reservoirs
    """

    reservoirs    = []
    pumps         = []
    resCons       = []
    pumpCons      = []

    try:

        # get information related to one reservoir
        if 'id' in req.GET :
            reservoirId = int(req.GET['id'])
            resCons  = Connection.objects \
                .filter(Q(reservoirA__res_id=reservoirId) | Q(reservoirB__res_id=reservoirId))
            pumpCons = PumpConnection.objects.filter(reservoir__res_id=reservoirId)
            res      = Reservoir.objects.filter(Q(res_id=reservoirId) | Q(res_id__in=resCons))
            pmps     = Pump.objects.filter(pump_id__in=pumpCons)
            
            resCons = resCons.values('pipingLength', 'maxFlow', 'flowDirection',
                'con_id', 'reservoirA__res_id', 'reservoirB__res_id')
            pumpCons = pumpCons.values('pipingLength', 'maxFlow', 'reservoir__res_id', 'pump__pump_id')
        
        # get information of reservoirs only in a particular region
        elif 'region' in req.GET :
            regionName = req.GET['region']
            res = Reservoir.objects.filter(
                Q(island__icontains=regionName) | 
                Q(county__icontains=regionName) | 
                Q(town__icontains=regionName))
            resCons = Connection.objects \
                .filter(Q(reservoirA_id__in=res) | Q(reservoirB_id__in=res)) \
                .values('pipingLength', 'maxFlow', 'flowDirection',
                'con_id', 'reservoirA__res_id', 'reservoirB__res_id')
            pumpCons = PumpConnection.objects.filter(reservoir_id__in=res)
            pmps     = Pump.objects.filter(pump_id__in=pumpCons)

            pumpCons = pumpCons.values('pipingLength', 'maxFlow', 'reservoir__res_id', 'pump__pump_id')

        else : # get all data
            res       = Reservoir.objects.all()
            pmps      = Pump.objects.all()
            pumpCons  = PumpConnection.objects \
                .values('pipingLength', 'maxFlow', 'reservoir__res_id', 'pump__pump_id')
            resCons = Connection.objects \
                .values('pipingLength', 'maxFlow', 'flowDirection',
                'con_id', 'reservoirA__res_id', 'reservoirB__res_id')

        for r in res :
            reservoirs.append({
                'id': r.res_id,
                'position': {'lat': r.latitude, 'lng': r.longitude},
                'address': r.addressName()
            })
        for p in pmps :
            pumps.append({
                'id': p.pump_id,
                'position': {'lat': p.latitude, 'lng': p.longitude},
                'address': p.addressName()
            })

    except Exception as e:
        print("[map] couldn't get data: {}".format(e))

    
    # check return type: return json data or the full page
    if 'res-type' in req.GET and req.GET['res-type'] == 'json' :
        data = {
            'reservoirs'     : reservoirs,
            'pumps'          : pumps,
            'reservoirCons'  : list(resCons),
            'pumpCons'       : list(pumpCons)
        }
        return HttpResponse(json.dumps(data))

    data = {
        'google_maps_key': settings.GOOGLE_MAPS_KEY,
        'reservoirs'     : json.dumps(reservoirs),
        'pumps'          : json.dumps(pumps),
        'reservoirCons'  : json.dumps(list(resCons)),
        'pumpCons'       : json.dumps(list(pumpCons))
    }
    template = loader.get_template('main/map.html')
    return HttpResponse(template.render(data, req))


@login_required(login_url='/login')
def reservoirList (req) :
    """
    Returns the page with the list of reservoirs
    """

    reservoirs = []
    islands    = []
    counties   = []
    try:
        reservoirs = Reservoir.objects.all()
        islands    = reservoirs.order_by().values_list('island', flat=True).distinct()
        counties   = reservoirs.order_by().values_list('county', flat=True).distinct()

        for r in reservoirs :
            r.setTemplateValues()
            # get the data from the last measurement from this reservoir
            try :
                r.lastMeasurement_ = Measurement.objects.filter(reservoir_id=r.res_id).latest('dateTime')
                r.waterVolume_     = r.lastMeasurement_.waterVolume()
            except Measurement.DoesNotExist :
                r.lastMeasurement_ = None
                r.waterVolume_ = 'Sem medições'

    except Exception as e:
        print("[reservoirList] couldn't get reservoir data: {}".format(e))

    template = loader.get_template('main/reservoirs_list.html')
    data = {
        'islands': islands,
        'counties': counties,
        'reservoirs': reservoirs
    }
    return HttpResponse(template.render(data, req))


@login_required(login_url='/login')
def reservoirDetailedInfo (req) :
    """
    Returns detailed information about the a reservoir and today's measurements
    """

    reservoirId = req.GET['id']
    try:
        reservoir = Reservoir.objects.get(res_id=reservoirId)
        reservoir.setTemplateValues()
        reservoir.totalCapacity_   = '{:.2f}'.format(reservoir.totalCapacity_)        
        # get the data from the last measurement from this reservoir
        try :
            reservoir.lastMeasurement_ = Measurement.objects.filter(
                reservoir_id=reservoir.res_id).latest('dateTime')
            reservoir.waterVolume_     = '{:.2f}'.format(reservoir.lastMeasurement_.waterVolume())
        except Measurement.DoesNotExist :
            reservoir.lastMeasurement_ = None
            reservoir.waterVolume_ = 'Sem medições'
        inputs  = InputPoint.objects.filter(reservoir_id=reservoir.res_id).values()
        outputs = OutputPoint.objects.filter(reservoir_id=reservoir.res_id).values()
    except Reservoir.DoesNotExist as e:
        print('[reservoirDetailedInfo] data for reservoir {} not found: {}'.format(reservoirId, e))
        raise Http404('Página não encontrada')

    data = {
        'reservoirState': reservoir, # will contain water level info, etc.
        'reservoir': json.dumps(model_to_dict(reservoir)), # won't contain current waterLevel, etc.
        'pictures': reservoir.allPics(),
        'inputs': json.dumps(list(inputs)),
        'outputs': json.dumps(list(outputs)),
    }

    template = loader.get_template('main/reservoir_info.html')
    return HttpResponse(template.render(data, req))


@login_required(login_url='/login')
def measurementData (req) :
    """
    Returns Measurements in json format
    """
    reservoirId =  'all'
    if 'res_id' in req.GET :
        reservoirId = req.GET['res_id']
    data          = req.GET['data']
    dateFrom      = req.GET['dateFrom']
    dateUntil     = req.GET['dateUnitl']
    clusterBy     = req.GET['clusterBy']

    # return JSON values
    measurements = Measurement.get(reservoirId, data, clusterBy, dateFrom, dateUntil)
    return HttpResponse(json.dumps(list(measurements)))


@login_required(login_url='/login')
def reservoirData (req) :
    """

main/templates/main/home.html
<!--
    user home page
-->

{% extends "main/home_base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles_home.css' %}">
    <title>Ouriço WMS</title>
{% endblock %}

{% block content %}
{% endblock %}

main/templates/main/home_base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/material.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles_global.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles_home_base.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/img/app_logo.png' %}"/>
    <link rel="manifest" href="{% static 'main/manifest.json' %}"/>
    {% block links %} {% endblock %}
    <script src="{% static 'main/js/material.js' %}"></script>
    <link   rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script src="{% static 'main/js/jquery-3.2.1.js' %}"></script>
    <script src="{% static 'main/js/js.cookie.js' %}"></script>
    <script src="{% static 'main/js/ws_util.js' %}"></script>
        <script src="{% static 'main/js/getmdl-select.min.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
        <div class="mdl-layout__drawer" id="left-nav">
            <a class="link-intro-page mdl-layout-title mdl-menu__item--full-bleed-divider" href="{% url 'main:home' %}">
                <div class="mdl-grid">
                    <div class="mdl-cell--4-col"><img id="app-logo" src="{% static 'main/img/app_logo.png' %}"/></div>
                    <div class="mdl-cell--8-col" id="app-title">Ouriço WMS</div>
                </div>
            </a>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link main-links" href="{% url 'main:reservoirList' %}">
                    <img class="material-icons nav-link" src="https://png.icons8.com/oil-storage-tank-filled/ios7/25"/>Reservatórios
                </a>
                <a class="mdl-navigation__link main-links" href="{% url 'main:map' %}">
                    <i class="material-icons nav-link">map</i>Mapa
                </a>
                <a class="mdl-navigation__link main-links" href="">
                    <i class="material-icons nav-link">timeline</i>Estatísticas Globais
                </a>
                <a class="mdl-navigation__link main-links" href="{% url 'main:doLogout' %}" id="logout-link" >
                    <i class="material-icons nav-link">arrow_back</i>Logout
                </a>
            </nav>
        </div>

        <main class="mdl-layout__content">
            <div class="page-content">
                {% block content %} {% endblock %}
            </div>
            <footer class="mdl-mini-footer">
                    <div class="mdl-mini-footer__left-section" id="copyrigth">
                        <ul class="mdl-mini-footer__link-list">
                        <li><a href="http://www.wellesley.edu">Wellesley College</a></li>
                        <li><a href="http://www.unicv.edu.cv">UniCV</a></li>
                        </ul>
                    </div>

                    <div class="mdl-mini-footer__right-section">
                        <div class="mdl-logo" id="copyright">&copy; WellesleyCollege &amp; UniCV</div>
                    </div>
                </footer>
        </main>
    </div>

    <!-- template for error dialog -->
    <dialog class="mdl-dialog" id="error-dialog">
      <h4 class="mdl-dialog__title">Erro</h4>
      <div class="mdl-dialog__content" id="error-dialog-content"></div>
      <div class="mdl-dialog__actions">
        <button type="button" class="mdl-button" id="error-dialog-bt-ok">Ok</button>
      </div>
    </dialog>

    <!-- template for message dialog -->
    <dialog class="mdl-dialog" id="msg-dialog">
      <h4 class="mdl-dialog__title" id="msg-dialog-title"></h4>
      <div class="mdl-dialog__content" id="msg-dialog-content"></div>
      <div class="mdl-dialog__actions">
        <button type="button" class="mdl-button" id="msg-dialog-bt-ok">Ok</button>
      </div>
    </dialog>

    <!-- template for choice dialog -->
    <dialog class="mdl-dialog" id="choice-dialog">
      <h4 class="mdl-dialog__title" id="choice-dialog-title"></h4>
      <div class="mdl-dialog__content" id="choice-dialog-content"></div>
      <div class="mdl-dialog__actions">
        <button type="button" class="mdl-button" id="choice-dialog-bt-ok">Ok</button>
        <button type="button" class="mdl-button" id="choice-dialog-bt-cancel">Cancelar</button>
      </div>
    </dialog>

  </body>
</html>

main/templates/main/login.html
<!--
    this is the login page
-->

{% extends "main/base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles_login.css' %}">
    <title>Login</title>
{% endblock %}

{% block content %}


<div class="main">

    <div class="transparency"></div>

    <a id="link-intro-page" href="{% url 'main:main' %}">
        <div class="mdl-grid">
            <div class="mdl-cell--4-col"><img id="app-logo" src="{% static 'main/img/app_logo.png' %}"/></div>
            <div class="mdl-cell--8-col" id="app-title">Ouriço WMS</div>
        </div>
    </a>


    <!-- Section with the login fields -->
    <div id="login-section" >
        {% csrf_token %}

        <div class="mdl-grid mdl-grid--no-spacing" id="login-section-grid">

            <div class="mdl-cell mdl-cell--4-row">
                <p id="login-text">Login</p>
            </div>

            <div class="mdl-cell mdl-cell--2-row">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" id="username-field">
                    <input class="mdl-textfield__input" type="text" id="username">
                    <label class="mdl-textfield__label" for="username">Nome de Utilizador</label>
                    <span class="mdl-textfield__error">Nome de Utilizador desconhecido</span>
                </div>
            </div>

            <div class="mdl-cell mdl-cell--2-row">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" id="password-field">
                    <input class="mdl-textfield__input" type="password" id="password">
                    <label class="mdl-textfield__label" for="password">Password</label>
                    <span class="mdl-textfield__error">Password errada</span>
                </div>
            </div>

            <div class="mdl-cell mdl-cell--2-row">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" id="bt-login" onclick="doLogin()">
                    Entrar
                </button>
            </div>
            
            <div class="mdl-cell mdl-cell--2-row">
                <a href="" class="mdl-navigation__link">Esqueceu-se da password?</a>
            </div>

        </div>
    </div>

</div>

<script hidden>
    // path to access the authentication function
    DO_LOGIN_PATH = "{% url 'main:doLogin' %}";
    // path for the home page
    HOME_PATH     = "{% url 'main:home' %}";
</script>

<!-- include scripts refering to this page -->
<script src="{% static 'main/js/ws_login.js' %}"></script>

{% endblock %}

main/templates/main/reservoir_data_export_dialog.html
{% load static %}

<dialog class="mdl-dialog" id="export-data-dialog">
    <h4 class="mdl-dialog__title">Exportar Dados</h4>
    <div class="mdl-dialog__content">
        <div class="mdl-grid">
            Escolher Reservatórios
            <div id="export-data-reservoir-list-container" class="mdl-cell--12-col-tablet">
                <ul class="mdl-list">
                    <li class="mdl-list__item">
                        <span class="mdl-list__item-primary-content">
                        Escolher Todos
                        </span>
                        <span class="mdl-list__item-secondary-action">
                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" 
                            for="export-data-reservoir-list-all">
                            <input type="checkbox" id="export-data-reservoir-list-all" 
                                class="mdl-checkbox__input" />
                        </label>
                        </span>
                    </li>
                </ul>
                <ul class="mdl-list" id="export-data-reservoir-list">
                </ul>
            </div>
        </div>
        <div class="mdl-grid mdl-grid--no-spacing" id="export-data-filters">
            <div class="mdl-cell mdl-cell--2-col-tablet">
                Dados Desde<input type="date" id="export-data-dateFrom" class="mdl-shadow--2dp">
            </div>
            <div class="mdl-cell mdl-cell--2-col-tablet">
                Dados Até<input type="date" id="export-data-dateUntil" class="mdl-shadow--2dp">
            </div>
        </div>
    </div>
    <div class="mdl-dialog__actions">
        <button type="button" class="mdl-button mdl-js-button" id="export-data-bt-csv">Exportar CSV</button>
        <button type="button" class="mdl-button mdl-js-button" id="export-data-bt-xls">Exportar XLS</button> 
        <button type="button" class="mdl-button mdl-js-button" id="export-data-bt-cancel">Cancelar</button> 
    </div>
</dialog>

<script>
    window.RESERVOIR_DATA_PATH = "{% url 'main:reservoirData' %}";
    window.EXPORT_DATA_PATH   = "{% url 'main:exportData' %}";
</script>

main/templates/main/reservoirs_list.html
<!--
    shows all info about the reservoirs
-->

{% extends "main/home_base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles_home_reservoirs.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/getmdl-select.min.css' %}">
    <title>Reservatórios</title>
{% endblock %}

{% block content %}
    <div id="main-grid">
        <div id="filters" class="mdl-shadow--2dp">
            <span>Filtrar Reservatórios</span>
            <div class="mdl-grid">
                <div id="island-filter" class="mdl-cell mdl-cell--2-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                    <input class="mdl-textfield__input" type="text" id="island" readonly tabIndex="-1">
                    <label for="island">
                        <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                    </label>
                    <label for="island" class="mdl-textfield__label">Ilha</label>
                    <ul for="island" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for island in islands %}
                        <li class="mdl-menu__item" data-val="{{ island }}">{{ island }}</li>
                    {% endfor %}
                    </ul>
                </div>

                <div id="county-filter" class="mdl-cell mdl-cell--2-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                    <input class="mdl-textfield__input" type="text" id="county" readonly tabIndex="-1">
                    <label for="county">
                        <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                    </label>
                    <label for="county" class="mdl-textfield__label">Concelho</label>
                    <ul for="county" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for county in counties %}
                        <li class="mdl-menu__item" data-val="{{ county }}">{{ county }}</li>
                    {% endfor %}
                    </ul>
                </div>

            </div>
        </div>
        <div id="list">
        {% for reservoir in reservoirs %}
            <div class="card mdl-card">
                <div class="mdl-grid mdl-grid--no-spacing card-info">
                    <div class="mdl-card__title mdl-card--expand mdl-cell mdl-cell--3-col"
                        style="background: url('{{ reservoir.mainPic_ }}') center / cover">
                    </div>
                    <div class="mdl-card__supporting-text mdl-cell mdl-cell--9-col">
                        <div class="card-info-val"><strong>Localização: </strong>{{ reservoir.addressName_ }}</div>
                        <div class="card-info-val"><strong>Capacidade Máxima: </strong>{{ reservoir.totalCapacity_ }} m³</div>
                        <div class="card-info-val"><strong>Quantidade de Água: </strong>{{ reservoir.waterVolume_ }} m³</div>
                    </div>
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <div class="mdl-layout-spacer"></div>
                    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                        href="{% url 'main:reservoirDetailedInfo' %}?id={{ reservoir.res_id }}">
                        <i class="material-icons card-button-icon">info</i>Mais Informação
                    </a>
                    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                        href="{% url 'main:map' %}?id={{ reservoir.res_id }}">
                        <i class="material-icons card-button-icon">map</i>Ver no Mapa
                    </a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

main/templates/main/stats.html
<!--

    TODO here:

    show stats of water volume per capita according to regions
    ...

-->